routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
 * 1- Admin Panel -> has a group of routes use roles middleware
 * 2- visitor to website can only show the index page
 * 3- normal user how has register before has group of routes use auth middleware
 * /////////////////////////   */


//!- A group of Route For DashBoard !
//    use => roles middleware ,
//    and the role must be admin.
Route::group(
    [
        'prefix' => 'admin',
        'middleware' => 'roles',
        'roles'=>'admin'
    ]
    ,function(){
        //!- Every Resource Controller include CRUD Operations
    Route::resource('users','AdminUsersController'); //!- Users Controller
    Route::resource('categories','AdminCategoriesController'); //!- Categories Controller
    Route::resource('semesters','AdminSemesterController'); //!- Semesters Controller
    Route::resource('types','AdminTypesController'); //!- Types of Posts Controller
    Route::resource('contactus','AdminContactusController'); //!-Contacts Controller
    Route::resource('posts','AdminPostsController'); //!- Posts Controller

        //!- TO get a specific Category ; use category_id to return a category with all data
    Route::get('category/{id}','PagesController@viewcategories')->name('viewcategories');

        //!- TO get a specific Type of Posts ; use Type_id to return a Type of post with all data
    Route::get('type/{id}','PagesController@viewtypes')->name('viewtypes');

        //!- create post need to choose a type recording to a category-- then you must choose a specific category first then choose the type of post
    Route::get('checkcategory/{id}','PagesController@checkcategory')->name('checkcategory');

        //!-active user from pagecontroller
    Route::post('active/{id}','PagesController@active')->name('active');

        //!-new users
    Route::get('newusers','PagesController@newusers')->name('newusers');
    Route::Post('newuseractive/{id}','PagesController@newuseractive')->name('newuseractive');
    //!- admin/admin open the main Page of admin panel AdminLTE
    Route::get('admin', function () {
        return view('admin.main');
    });
});


//!- group of route for the user who has auth--
// use auth middleware.
Route::group(
    [
        'prefix'=>'academy',
        'middleware'=>['auth','roles'],
        'role'=>['admin','user'],
    ]
    ,function(){


    Route::get('group/{id}','PagesController@group')->name('group'); //!-posts in category
    Route::get('subofgroup/{id}','PagesController@subofgroup')->name('subofgroup'); //!-every category has types here we return the posts for the Type_id -> {id}
    Route::resource('comments','UsersCommentsController'); //!- comments controller with CRUD operations
});

//!- Authentication Route
Auth::routes();

//!- the Main page for user
Route::get('/home', 'HomeController@index')->name('home');


//!- Index page the Main page in the website for a normal visitor
Route::get('/', function () {
    return view('index');//welcome
});


Route::get('poster/{parameter}','PagesController@poster')->name('poster'); //!- find post

resources/views/admin/choosecategoryofpost.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>post type</h1>
@endsection

@section('content')
    <div class="box box-solid box-default">
        <div class="box-header with-border">
            <h3 class="box-title">choose category type</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->

            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <fieldset>
                <legend>Categories</legend>
                @foreach($categorz as $category)
                    <a href="{{route('checkcategory',$category->id)}}">
                        <button type="button" class="btn btn-info">{{$category->name}}</button>
                    </a>
                @endforeach
            </fieldset>

        </div>
        <!-- /.box-body -->
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/contactus.blade.php
<?php
$i=1;
?>
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Contact US</h1>
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Contacts Table</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->

                <a class="btn btn-success" href="{{route('contactus.create')}}">ADD Contact</a>

            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if(session('msg'))
                <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                    <div class="card-header">Success {{session('msg')}}</div>
                </div>
            @endif

            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Edara</th>
                    <th scope="col">phone 1</th>
                    <th scope="col">phone 2</th>
                    <th scope="col">Email</th>
                    <th scope="col">Description</th>
                    <th scope="col">Title</th>
                    <th scope="col" colspan="2" style="text-align: center">modify</th>
                </tr>
                </thead>
                <tbody>

                @if(count($contacts)>0)

                    @foreach($contacts as $contact)

                        <tr class="table-success">
                            <th scope="row">{{$i++}}</th>
                            <td>{{$contact->edara}}</td>
                            <td>{{$contact->phone1}}</td>
                            <td>{{$contact->phone2}}</td>
                            <td>{{$contact->email}}</td>
                            <td>{{$contact->description}}</td>
                            <td>{{$contact->title}}</td>
                            <td style="text-align: center"><a href="{{route('contactus.edit',$contact->id)}}">
                                    <button type="button" class="btn btn-info">Edit</button></a></td>
                            <td style="text-align: center">
                                <form action="{{route('contactus.destroy',$contact->id)}}" method="post">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}

                                    <button onclick="return confirm('Are you sure you want to Remove?');" type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <span>Num of Rec:</span> &nbsp; <mark>{{count($contacts)}}</mark>
        </div>
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/createcategory.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Users</h1>
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Create Category</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="panel-body">
            <form autocomplete="off" action="{{route('categories.store')}}" method="post">
                {{csrf_field()}}

                    <input type="text" name="name" class="form-control" placeholder="Category Name" id="inputDefault">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    <br>
                    <button type="submit" class="btn btn-primary">Create</button>

            </form>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/createsemesters.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Semesters</h1>
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Create Semester</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="panel-body">
                <form autocomplete="off" action="{{route('semesters.store')}}" method="post">
                    {{csrf_field()}}

                    <input type="text" name="name" class="form-control" placeholder="Semester Name" id="inputDefault">
                    @if ($errors->has('name'))
                        <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                    <br>
                    <button type="submit" class="btn btn-primary">Create</button>

                </form>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/createtypes.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Types</h1>
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Create Type</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="panel-body">
                <form autocomplete="off" action="{{route('types.store')}}" method="post">
                    {{csrf_field()}}
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="col-md-4 control-label">type name</label>

                        <input type="text" name="name" class="form-control" placeholder="Type Name" id="inputDefault">
                        @if ($errors->has('name'))
                            <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                    <div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
                        <label for="category" class="col-md-4 control-label">category</label>

                        <select name="category" required>
                        @foreach($categorz as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                        @endforeach
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Create</button>

                </form>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/main.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Main</h1>
@endsection

@section('content')

    <p>Welcome to this beautiful admin panel.</p>
    <div class="box box-solid box-default">
        <div class="box-header with-border">
            <h3 class="box-title">All Pages</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="row featurette">
                <div class="col-md-7 order-md-2">
                    <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
                    <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
                </div>
                <div class="col-md-5 order-md-1">
                    <a href="{{route('users.index')}}" class="btn btn-success col-md-12 margin-bottom">users</a>
                    <a href="{{route('categories.index')}}" class="btn btn-warning col-md-12 margin-bottom">categories</a>
                    <a href="{{route('types.index')}}" class="btn btn-info col-md-12 margin-bottom">types</a>
                    <a href="{{route('contactus.index')}}" class="btn btn-danger col-md-12 margin-bottom">contacts</a>
                    <a href="{{route('semesters.index')}}" class="btn btn-primary col-md-12 margin-bottom">semesters</a>
                    <a href="{{route('posts.index')}}" class="btn btn-success col-md-12 margin-bottom">posts</a>
                </div>
            </div>
        </div>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->
@endsection

resources/views/admin/semesters.blade.php
<?php
$i=1;
?>
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Semesters</h1>
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Semesters Table</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->

                <a class="btn btn-success" href="{{route('semesters.create')}}">ADD Semesters</a>

            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if(session('msg'))
                <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                    <div class="card-header">Success {{session('msg')}}</div>
                </div>
            @endif

            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">name</th>
                    <th scope="col" colspan="2" style="text-align: center">modify</th>
                </tr>
                </thead>
                <tbody>

                @if(count($semesters)>0)

                    @foreach($semesters as $semester)

                        <tr class="table-success">
                            <th scope="row">{{$i++}}</th>
                            <td>{{$semester->name}}</td>
                            <td style="text-align: center"><a href="{{route('semesters.edit',$semester->id)}}">
                                    <button type="button" class="btn btn-info">Edit</button></a></td>
                            <td style="text-align: center">
                                <form action="{{route('semesters.destroy',$semester->id)}}" method="post">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}

                                    <button onclick="return confirm('Are you sure you want to Remove?');" type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">

                <span>Num of Rec:</span> &nbsp; <mark>{{count($semesters)}}</mark>

        </div>
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/types.blade.php
<?php
$i=1;
?>
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Types</h1>
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Types Table</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->

                <a class="btn btn-success" href="{{route('types.create')}}">ADD Types</a>

            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if(session('msg'))
                <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                    <div class="card-header">Success {{session('msg')}}</div>
                </div>
            @endif

            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Type Name</th>
                    <th scope="col">category Name</th>
                    <th scope="col" colspan="2" style="text-align: center">modify</th>
                </tr>
                </thead>
                <tbody>

                @if(count($types)>0)

                    @foreach($types as $type)

                        <tr class="table-success">
                            <th scope="row">{{$i++}}</th>
                            <td>{{$type->name}}</td>
                            <td>{{$type->category->name}}</td>
                            <td style="text-align: center"><a href="{{route('types.edit',$type->id)}}">
                                    <button type="button" class="btn btn-info">Edit</button></a></td>
                            <td style="text-align: center">
                                <form action="{{route('types.destroy',$type->id)}}" method="post">
                                    {{csrf_field()}}
                                    {{method_field('DELETE')}}

                                    <button onclick="return confirm('Are you sure you want to Remove?');" type="submit" class="btn btn-danger">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <span>Num of Rec:</span> &nbsp; <mark>{{count($types)}}</mark>
        </div>
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/users.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <div style="position: absolute;right: 10px" class="m-4">
        <a href="{{route('newusers')}}" class="btn btn-danger" style="margin: 5px">
            <span>New+ {{\App\User::where('isnew','=','true')->count()}}</span>
        </a>
    </div>
    <div class="col-md-1">
        <h3>Users</h3>
    </div>

@endsection

@section('content')

    <div class="form-group m-2">
        <form action="{{ route('users.index') }}" method="get">

            <div class="row">

                <div class="col-md-4">
                   <input type="text" name="search" class="form-control" placeholder="search by Name" value="{{ request()->search }}">
                </div>
                <div class="col-md-4">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i> search</button>
                </div>

            </div>
        </form><!-- end of form -->
    </div>
    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">Users Table</h3>
            <div class="box-tools pull-right">
                <!-- Buttons, labels, and many other things can be placed here! -->
                <!-- Here is a label for example -->
            </div>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if(session('msg'))
                <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
                    <div class="card-header">Success {{session('msg')}}</div>
                </div>
            @endif
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">name</th>
                    <th scope="col">email</th>
                    <th scope="col">description</th>
                    <th scope="col" colspan="2" style="text-align: center">modify</th>
                    <th scope="col" colspan="3" style="text-align: center">status</th>
                </tr>
                </thead>
                <tbody>

                @if(count($users)>0)
                    @foreach($users as $index=>$user)
                        @if($user->isnew =='false')
                            <tr class="table-success">
                                <th scope="row">{{$index+1}}</th>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    @foreach($user->roles as $role)
                                        @if(count($user->roles)>1)
                                            [{{$role->name}}]
                                        @else
                                            {{$role->name}}
                                        @endif
                                    @endforeach
                                </td>
                                <td style="text-align: center"><a href="{{route('users.edit',$user->id)}}">
                                        <button type="button" class="btn btn-info">Edit</button></a></td>
                                <td style="text-align: center">
                                    <form action="{{route('users.destroy',$user->id)}}" method="post">
                                        {{csrf_field()}}
                                        {{method_field('DELETE')}}

                                        <button onclick="return confirm('Are you sure you want to Remove?');" type="submit" class="btn btn-danger">Delete</button>

                                    </form>
                                </td>
                                <td style="text-align: center">
                                    <form action="{{route('active',$user->id)}}" method="post">
                                        {{csrf_field()}}
                                        @if($user->status==1)
                                        <input checked type="radio" value="1" name="active">active |
                                        <input type="radio" value="0" name="active">disactive
                                        @else
                                        <input  type="radio" value="1" name="active">active |
                                        <input checked type="radio" value="0" name="active">disactive
                                        @endif
                                        <button type="submit" class="margin btn btn-warning">change status</button>

                                    </form>
                                </td>
                            </tr>
                        @endif
                    @endforeach
                @else
                    <h1>not found</h1>
                @endif
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <div style="width: 100%;text-align: center">
                {{ $users->appends(request()->query())->links() }}
            </div>
        </div>
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/viewcategory.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Posts</h1>
    @include('admin.postsnav')
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">{{$category->name}}</h3>
            <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if(count($posts)>0)
                <div class="row">
                    @foreach($posts as $post)
                        <div class="col-md-4">
                            <ul class="thumbnail">
                                <div class="panel panel-info">
                                    <div class="panel-heading text-center">{{$post->title}}</div>
                                    <div class="panel-body">
                                        <img src="{{asset('storage/thumbnails/'.$post->image)}}" alt="Lights" class="img-thumbnail" style="height: 250px !important;">
                                    </div>
                                </div>
                                <ul class="breadcrumb">
                                    <li>{{$post->category->name}}</li>
                                    <li class="active">{{$post->type->name}}</li>
                                    <li>{{$post->semester->name}}</li>
                                </ul>
                                <blockquote style="height: 218px;">
                                    <p>{{$post->info}}</p>
                                    <small>{{$post->time}} &nbsp;//<cite title="Source Title">{{$post->year}}</cite></small><br>
                                    <form action="{{route('posts.destroy',$post->id)}}" method="post">
                                        {{csrf_field()}}
                                        {{method_field('DELETE')}}
                                        <button onclick="return confirm('Are you sure you want to Remove?');" type="submit" class="btn btn-danger">Remove Post</button>
                                    </form>
                                </blockquote>
                                <div class="btn-group btn-group-justified">
                                    <a href="{{route('posts.edit',$post->id)}}" class="btn btn-info">Edit Post</a>
                                </div>
                            </ul>
                        </div>
                    @endforeach
                </div>
            @endif
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <span>Num of Posts:</span> &nbsp; <mark>{{count($posts)}}</mark>
        </div>
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection

resources/views/admin/viewtype.blade.php
@extends('adminlte::page')

@section('title', 'Academy')

@section('content_header')
    <h1>Posts</h1>
    @include('admin.postsnav')
@endsection

@section('content')

    <div class="box box-solid">
        <div class="box-header with-border">
            <h3 class="box-title">{{$type->name}}</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            @if(count($posts)>0)
                <div class="row">
                    @foreach($posts as $post)
                        <div class="col-md-4">
                            <ul class="thumbnail">
                                <div class="panel panel-info">
                                    <div class="panel-heading text-center">{{$post->title}}</div>
                                    <div class="panel-body">
                                        <img src="{{asset('storage/thumbnails/'.$post->image)}}" alt="Lights" class="img-thumbnail" style="height: 250px !important;">
                                    </div>
                                </div>
                                <ul class="breadcrumb">
                                    <li>{{$post->category->name}}</li>
                                    <li class="active">{{$post->type->name}}</li>
                                    <li>{{$post->semester->name}}</li>
                                </ul>
                                <blockquote style="height: 218px;">
                                    <p>{{$post->info}}</p>
                                    <small>{{$post->time}} &nbsp;//<cite title="Source Title">{{$post->year}}</cite></small><br>
                                    <form action="{{route('posts.destroy',$post->id)}}" method="post">
                                        {{csrf_field()}}
                                        {{method_field('DELETE')}}
                                        <button onclick="return confirm('Are you sure you want to Remove?');" type="submit" class="btn btn-danger">Remove Post</button>
                                    </form>
                                </blockquote>
                                <div class="btn-group btn-group-justified">
                                    <a href="{{route('posts.edit',$post->id)}}" class="btn btn-info">Edit Post</a>
                                </div>
                            </ul>
                        </div>
                    @endforeach
                </div>
            @endif
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            <span>Num of Posts:</span> &nbsp; <mark>{{count($posts)}}</mark>
        </div>
        <!-- box-footer -->
    </div>
    <!-- /.box -->
@endsection