routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
 * 1- Admin Panel -> has a group of routes use roles middleware
 * 2- visitor to website can only show the index page
 * 3- normal user how has register before has group of routes use auth middleware
 * /////////////////////////   */


//!- A group of Route For DashBoard !
//    use => roles middleware ,
//    and the role must be admin.
Route::group(
    [
        'prefix' => 'admin',
        'middleware' => 'roles',
        'roles'=>'admin'
    ]
    ,function(){
        //!- Every Resource Controller include CRUD Operations
    Route::resource('users','AdminUsersController'); //!- Users Controller
    Route::resource('categories','AdminCategoriesController'); //!- Categories Controller
    Route::resource('semesters','AdminSemesterController'); //!- Semesters Controller
    Route::resource('types','AdminTypesController'); //!- Types of Posts Controller
    Route::resource('contactus','AdminContactusController'); //!-Contacts Controller
    Route::resource('posts','AdminPostsController'); //!- Posts Controller

        //!- TO get a specific Category ; use category_id to return a category with all data
    Route::get('category/{id}','PagesController@viewcategories')->name('viewcategories');

        //!- TO get a specific Type of Posts ; use Type_id to return a Type of post with all data
    Route::get('type/{id}','PagesController@viewtypes')->name('viewtypes');

        //!- create post need to choose a type recording to a category-- then you must choose a specific category first then choose the type of post
    Route::get('checkcategory/{id}','PagesController@checkcategory')->name('checkcategory');

        //!-active user from pagecontroller
    Route::post('active/{id}','PagesController@active')->name('active');

        //!-new users
    Route::get('newusers','PagesController@newusers')->name('newusers');
    Route::Post('newuseractive/{id}','PagesController@newuseractive')->name('newuseractive');
    //!- admin/admin open the main Page of admin panel AdminLTE
    Route::get('admin', function () {
        return view('admin.main');
    });
});


//!- group of route for the user who has auth--
// use auth middleware.
Route::group(
    [
        'prefix'=>'academy',
        'middleware'=>['auth','roles'],
        'role'=>['admin','user'],
    ]
    ,function(){


    Route::get('group/{id}','PagesController@group')->name('group'); //!-posts in category
    Route::get('subofgroup/{id}','PagesController@subofgroup')->name('subofgroup'); //!-every category has types here we return the posts for the Type_id -> {id}
    Route::resource('comments','UsersCommentsController'); //!- comments controller with CRUD operations
});

//!- Authentication Route
Auth::routes();

//!- the Main page for user
Route::get('/home', 'HomeController@index')->name('home');


//!- Index page the Main page in the website for a normal visitor
Route::get('/', function () {
    return view('index');//welcome
});


Route::get('poster/{parameter}','PagesController@poster')->name('poster'); //!- find post

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    //!- user belongs to many roles and role belongs to many users
    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    //!- user  has many comments
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    //!-check user roles
    public function hasAnyRole($roles)
    {
        //!-if user array roles
        if (is_array($roles))
        {
            foreach ($roles as $role)
            {
                if ($this->hasRole($role))
                {
                    return true;
                }
            }
        }
        else
        {
            //!-if user role
            if ($this->hasRole($roles))
            {
                return true;
            }
        }
        return false;
    }

    //!-if user one role
    public function hasRole($role)
    {
        if ($this->roles()->where('name',$role)->first())
        {
            return true;
        }
        return false;
    }
}

resources/views/user/editcomment.blade.php
@extends('user.header')
@section('nav')
    @include('user.nav')
@endsection
@section('content')
<div class="container">
    <!-- Single Comment -->
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Edit</h3>
        </div>
        <div class="panel-body">
            <div class="card my-4">
                <h5 class="card-header">Leave a Comment:</h5>
                <div class="card-body">
                    <form autocomplete="off" action="{{route('comments.update',Crypt::encrypt($bcomment->id))}}" method="post">
                        {{csrf_field()}}
                        {{method_field('PUT')}}
                        <div class="form-group{{ $errors->has('editcomment') ? ' has-error' : '' }}">
                            <textarea autofocus id="comment" name="editcomment" class="form-control" maxlength="200" style="max-height: 100px;min-height: 100px">{{$bcomment->comment}}</textarea>
                            @if ($errors->has('comment'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('editcomment') }}</strong>
                                </span>
                            @endif
                        </div>
                        <input type="hidden" value="{{Crypt::encrypt($bcomment->post_id)}}" name="pid">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/footer.blade.php
<!-- Footer -->
<footer class="py-4 bg-dark">

    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MN-2019</p>
    </div>
    <!-- /.container -->
</footer>

resources/views/user/group.blade.php
@extends('user.header')
@section('nav')
    @include('user.nav')
@endsection
@section('content')

    <!-- Page Content -->
<div class="container">

    <div class="row">

        <!-- /.col-lg-3 -->

        <div class="col-lg-12">

            <div class="card mt-4">
                <div class="card-body">
                    <h3 class="card-title">{{$group->name}}</h3>
                </div>
            </div>
            <!-- /.card -->

            <div class="card card-outline-secondary my-4">
                <div class="card-header">
                    POSTS
                </div>
                <div class="card-body">
                    @if(count($postes)>0)
                        @foreach($postes as $post)
                            @if($post->status==1)
                                <h3>{{ $post->title }}</h3>
                                <p class="text-muted">{{ $post->info }}</p>
                                <small>{{ $post->time }}</small>

                                <a class="view" href="{{ route('poster',Crypt::encrypt($post->id)) }}">View</a>
                            <hr>
                            @endif
                        @endforeach
                    @endif
                </div>
            </div>
            <!-- /.card -->

        </div>
        <!-- /.col-lg-9 -->

    </div>

</div>
<!-- /.container -->

@endsection

resources/views/user/header.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ config('app.name', 'Laravel') }}</title>
    <link rel="icon" type="image/png" href="{{ URL::asset('images/mainicon.png') }}">
    <!-- Styles -->
    <link href="{{ asset('css/bootstrap.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ URL::asset('bootstrap/bootstrap.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!--js-->
    <script src="../../public/js/gulpfile.js"></script>
    <style>
        body{
            padding-top: 75px;
        }
        .view{
            display: block;
            font-size: 15px;
            border: 3px solid #4c7689;
            padding: 5px;
            color: #000;
            text-align: center;
            margin: 5px;
        }
        .view:hover{
            background-color: #1e7d98;
            color: #FFF;
            text-decoration: none;
        }
    </style>
</head>

<body>
    @yield('nav')
    @yield('content')
    @yield('footer')
    <!-- Bootstrap core JavaScript -->
    <script src="{{ URL::asset('vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ URL::asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
</body>
</html>

resources/views/user/nav.blade.php
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand text-uppercase" style="font-size: xx-large" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <li class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                @if (Auth::guest())
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/#about_us') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('/#contact') }}">Contact</a>
                    </li>

                    <li class="nav-item"><a class="nav-link" href="{{ route('login') }}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ route('register') }}">Register</a></li>
                @else
                    <li class="nav-item active">
                        <a class="nav-link" href="{{route('home')}}">Home
                        </a>
                    </li>
                    @foreach($categorz as $category)
                        @if($category->name=='Scientific Research' || $category->name=='Tables' || $category->name=='Department')
                            @continue
                        @else
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ $category->name }}</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown01">
                                    @foreach($types as $type)
                                        @if($type->category_id==$category->id)
                                            <a class="dropdown-item" href="{{ route('subofgroup',$type->id) }}">{{ $type->name }}</a>
                                        @endif
                                    @endforeach
                                </div>
                            </li>
                        @endif
                    @endforeach
                    <li class="nav-item">

                        <a class="nav-link" href="{{ route('logout') }}"
                           onclick="event.preventDefault();document.getElementById('logout-form').submit(); ">
                            Logout
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>

                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/user/poster.blade.php
@extends('user.header')
@section('nav')
    @include('user.nav')
@endsection
@section('content')

    <!-- Page Content -->
    <div class="container">

        <div class="row">

                <!-- Post Content Column -->
                <div class="col-lg-12">

                    <!-- Title -->
                    <h1 class="mt-4">{{ $poster->title }}</h1>

                    <!-- Author -->
                    <p class="lead">
                        by
                        <a href="{{ route('group',$poster->category->id) }}">{{ $poster->category->name }}</a>
                    </p>

                    <hr>

                    <!-- Date/Time -->
                    <p>Posted on {{ $poster->year }}, {{ $poster->time }}</p>

                    <hr>

                    <!-- Preview Image -->
                    <img class="img-fluid rounded" style="width:100%;height:400px;margin: 0 auto" src="{{ asset('storage/thumbnails/'.$poster->image) }}" alt="{{ $poster->title }}">

                    <hr>

                    <!-- Post Content -->
                    <p class="lead">{{ $poster->info }}</p>
                    <blockquote class="blockquote">
                        <p class="mb-0"></p>
                        <footer class="blockquote-footer">Section: &nbsp;{{ $poster->type->name }} &triangleright;
                            <cite title="Source Title">{{ $poster->semester->name }} Semester</cite>
                        </footer>
                    </blockquote>
                    <hr>
                    @if(Auth::user() && Auth::user()->status==1 )
                        <!-- Comments Form -->
                        <div class="card my-4">
                            <h5 class="card-header">Leave a Comment:</h5>
                            <div class="card-body">
                                <form autocomplete="off" action="{{route('comments.store')}}" method="post">
                                    {{csrf_field()}}

                                    <div class="form-group{{ $errors->has('comment') ? ' has-error' : '' }}">
                                        <textarea id="comment" name="comment" class="form-control" maxlength="200" style="max-height: 100px;min-height: 100px"></textarea>
                                        @if ($errors->has('comment'))
                                            <span class="help-block">
                                                <strong>{{ $errors->first('comment') }}</strong>
                                            </span>
                                        @endif
                                    </div>

                                    <input type="hidden" value="{{ Crypt::encrypt($poster->id) }}" name="post_id">
                                    <button type="submit" class="btn btn-primary">Comment</button>
                                </form>
                            </div>
                        </div>

                        <!-- Single Comment -->
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Comments</h3>
                            </div>
                            <div class="panel-body">
                                @foreach($comments as $comment)
                                    @if($comment->post_id==$poster->id)
                                        <div class="media mb-4">
                                            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
                                            <div class="media-body">
                                                <h5 class="mt-0">{{ $comment->user->name }}</h5>
                                                {{ $comment->comment }}
                                            </div>
                                            @if($comment->user->id==Auth::user()->id)
                                                <div class="m-4">
                                                    <a href="{{ route('comments.edit',Crypt::encrypt($comment->id)) }}">
                                                        <button style="background-color: #FFF;border: none"><i class="fas fa-edit"></i></button>
                                                    </a>

                                                </div>
                                                <div class="m-4">
                                                    <form action="{{ route('comments.destroy',Crypt::encrypt($comment->id)) }}" method="post">
                                                        {{csrf_field()}}
                                                        {{method_field('DELETE')}}
                                                        <button style="background-color: #FFF;border: none"  onclick="return confirm('Are you sure you want to Remove?');" type="submit"><i class="fas fa-trash-alt"></i></button>
                                                    </form>
                                                </div>
                                            @endif
                                        </div>
                                        <hr>
                                    @endif
                                @endforeach
                            </div>
                        </div>
                    @endif
                </div>
            </div>

        <!-- /.row -->
    </div>
    <!-- /.container -->


@endsection
@section('footer')
    @include('user.footer')
@endsection

resources/views/user/subofgroup.blade.php
@extends('user.header')
@section('nav')
    @include('user.nav')
@endsection
@section('content')

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- /.col-lg-3 -->

            <div class="col-lg-12">

                <div class="card mt-4">
                    <div class="card-body">
                        <h3 class="card-title">{{$sub->name}}</h3>
                    </div>
                </div>
                <!-- /.card -->

                <div class="card card-outline-secondary my-4">
                    <div class="card-header">
                        POSTS
                    </div>
                    <div class="card-body">
                        @foreach($postes as $post)
                            <h3>{{ $post->title }}</h3>
                            <p class="text-muted">{{ $post->info }}</p>
                            <small>{{ $post->time }}</small>
                            <a class="view" href="{{ route('poster',Crypt::encrypt($post->id)) }}">View</a>
                            <hr>
                        @endforeach
                    </div>
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col-lg-9 -->

        </div>

    </div>
    <!-- /.container -->

@endsection